version: '3'
services:
  db:
    image: mysql:5.7
    container_name: todo-db
    environment:
      MYSQL_ROOT_PASSWORD: ssi
      MYSQL_DATABASE: tododb
      MYSQL_USER: ssi
      MYSQL_PASSWORD: ssi
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: todo-php
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8088:80
volumes:
  dbdata: